const data = [
    {
      courseStartdate: "2023-09-01T08:00:00.000Z",
      jobRole: "Framework Engineer",
      courseName: "HTML",
      courseUrl: "https://example.com/course1",
      courseDuration: 2,
      description: "Description for Course 1",
      assignmentUrl: "https://example.com/assignment1",
      assessmentUrl: "https://example.com/assessment1",
    },
    {
      courseStartdate: "2023-09-01T08:00:00.000Z",
      jobRole: "Framework Engineer",
      courseName: "CSS",
      courseUrl: "https://example.com/course2",
      courseDuration: 1,
      description: "Description for Course 2",
      assignmentUrl: "https://example.com/assignment2",
      assessmentUrl: "https://example.com/assessment2",
    },
    {
      courseStartdate: "2023-09-05T08:00:00.000Z",
      jobRole: "Framework Engineer",
      courseName: "JavaScript",
      courseUrl: "https://example.com/course3",
      courseDuration: 3,
      description: "Description for Course 3",
      assignmentUrl: "https://example.com/assignment3",
      assessmentUrl: "https://example.com/assessment3",
    },
    {
      courseStartdate: "2023-09-08T08:00:00.000Z",
      jobRole: "Framework Engineer",
      courseName: "Python",
      courseUrl: "https://example.com/course4",
      courseDuration: 3,
      description: "Description for Course 4",
      assignmentUrl: "https://example.com/assignment4",
      assessmentUrl: "https://example.com/assessment4",
    },
    {
      courseStartdate: "2023-09-01T08:00:00.000Z",
      jobRole: "Data Engineer",
      courseName: "DATABASE",
      courseUrl: "https://example.com/course5",
      courseDuration: 3,
      description: "Description for Course 5",
      assignmentUrl: "https://example.com/assignment5",
      assessmentUrl: "https://example.com/assessment5",
    },
    {
      courseStartdate: "2023-09-06T08:00:00.000Z",
      jobRole: "Data Engineer",
      courseName: "SQL",
      courseUrl: "https://example.com/course6",
      courseDuration: 3,
      description: "Description for Course 6",
      assignmentUrl: "https://example.com/assignment6",
      assessmentUrl: "https://example.com/assessment6",
    },
    
    {
      courseStartdate: "2023-09-11T08:00:00.000Z",
      jobRole: "Framework Engineer",
      courseName: "Java",
      courseUrl: "https://example.com/course8",
      courseDuration: 3,
      description: "Description for Course 8",
      assignmentUrl: "https://example.com/assignment8",
      assessmentUrl: "https://example.com/assessment8",
    },
]
module.exports= data;